[package]
name = "pallet-transaction-storage"
version = "27.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Storage chain pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { optional = true, workspace = true, default-features = true }
codec = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
serde = { optional = true, workspace = true, default-features = true }
frame = { workspace = true, features = ["experimental", "runtime"] }
pallet-balances = { workspace = true }
sp-transaction-storage-proof = { workspace = true }
log = { workspace = true }

[dev-dependencies]
sp-transaction-storage-proof = { default-features = true, workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"array-bytes",
	"frame/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
]
std = [
	"codec/std",
	"frame/std",
	"log/std",
	"pallet-balances/std",
	"scale-info/std",
	"serde",
	"sp-transaction-storage-proof/std",
]
try-runtime = [
	"frame/try-runtime",
	"pallet-balances/try-runtime",
]
